version: '3.1'

services:
  mongo:
    image: mongo
    container_name: my-mongo-container
    ports:
      - "27013:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: my_db
    volumes:
      - ./data:/data/db
