version: '2.3'
services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "trip_db"
      POSTGRES_USER: "taxi_admin"
      POSTGRES_PASSWORD: "pswd"
    ports:
      - "5432:5432"

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    env_file:
      - kafka/kafka-variables.env
    depends_on:
      - zookeeper
    ports:
      - '9093:9092'
      - '8082:8082'
      - '8083:8083'

#  mongo-db:
#    image: mongo:4.0
#    expose:
#      - "27017"
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_DATA_DIR: /data/db
#      MONGO_LOG_DIR: /dev/null

#  consumer-mongo-db:
#    build:
#      context: consumer-mongo-db
#    environment:
#      mongoURL: mongodb://mongo-db:27017
#      dbName: example_db
#      collectionName: example_coll
#      kafkaURL: kafka:9092
#      topic: topic1
#      GroupID: mongo-group
#    depends_on:
#      - kafka
#      - mongo-db

  tripsvc-consumer:
    build:
      context: consumer-tripsvc
    environment:
      kafkaURL: kafka:9092
      topic: upd_trip
      GroupID: trip-upd-group
    depends_on:
      - kafka

  client-producer:
    build:
      context: producer-client
    environment:
      kafkaURL: kafka:9092
      topic: upd_trip
    depends_on:
      - kafka

#  driver-producer:
#    build:
#      context: producer-client
#    environment:
#      kafkaURL: kafka:9092
#      topic: upd_trip
#    depends_on:
#      - kafka

#  producer-api:
#    build:
#      context: producer-api
#    environment:
#      kafkaURL: kafka:9092
#      topic: topic1
#    expose:
#      - "8080"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka